### ISSUE TITLE
Outdated Database 

### ISSUE THREAD

**Issue by zouyl14** [modestyachts/imagenet-testbed#8]
I wanted to download the model prediction data.  However, it turns out that the URL(https://vasa.millennium.berkeley.edu:9000/robustness-eval/robustness_evalutation.db) is outdated and can not be connected. Is there any new link that should be updated?

**Comment by rtaori** [comment]
Ah sorry about this. It seems like the server went down sometime over break - I'm in contact with the IT admin to try and figure out what's going on. In the meantime, I've uploaded the file here https://drive.google.com/file/d/17XOxNxRqB_xMcHsAoewNmtuzKtdlpmzV/view?usp=sharing for you to download - just place it in `imagenet-testbed/s3_cache/robustness_evaluation.db`. All the metrics information is stored in here, and most of the model and dataset checkpoints are stored in a google cloud bucket so those should work as well. A few of the latest models/evaluation data added is still stored on the Berkeley server so that won't be available until the server is back up. Sorry about that! And let me know if this patch works.

**Comment by rtaori** [comment]
The server should be up now. Please let me know if you run into any more issues.

**Comment by zouyl14** [comment]
Many thanks!

**Comment by nng555** [comment]
Looks like the DB is down again unfortunately
